GET https://api.odcloud.kr/api/15109950/v1/uddi:1f78fe49-78b4-4784-a5f0-e2c8a60515b4?page=1&perPage=3&serviceKey=KoDtJsVKUjPCWeuISpoKkT00zTW1%2FT3bQqcSDAI1ke1TqfceIic%2FUxLJF6wyx0IrGKkFWZGNevdFQ08jWlE7vg%3D%3D